SELECT TOP (1000) [CustomerKey]
      ,[Gender]
      ,[Title]
      ,[GivenName]
      ,[MiddleInitial]
      ,[Surname]
      ,[StreetAddress]
      ,[City]
      ,[State]
      ,[StateFull]
      ,[ZipCode]
      ,[Country]
      ,[CountryFull]
      ,[Birthday]
      ,[Age]
      ,[Occupation]
      ,[Company]
      ,[Vehicle]
      ,[Latitude]
      ,[Longitude]
      ,[Continent]
  FROM [Contoso10K].[Data].[Customer]